# Generated by Django 2.1.4 on 2018-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='principleName',
            new_name='principle',
        ),
    ]
